[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@shine/=src/', '@solady/=lib/solady/src/', 'testing/=test/']
viaIR = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
